[package]
name    = "nfoxide"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow          = "1.0.98"
clap            = "4.5.40"
inquire         = "0.7.5"
minijinja       = "2.10.2"
minijinja-embed = "2.10.2"
regex           = "1.11.1"

[build-dependencies]
minijinja-embed = "2.10.2"
